/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movil;

import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class Interfaz extends javax.swing.JFrame {

    Cellphone cellphone = new Cellphone();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBatery = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAcoutBalance = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblOn = new javax.swing.JLabel();
        btnOnOf = new javax.swing.JButton();
        btnChargeCellphone = new javax.swing.JButton();
        btnRechargeAcountBalance = new javax.swing.JButton();
        btnUseCellphone = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();
        txtNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, -1, -1));

        jLabel3.setText("Bateria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 40, -1, -1));

        lblBatery.setText("----------");
        getContentPane().add(lblBatery, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel5.setText("Saldo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 63, -1, -1));

        lblAcoutBalance.setText("----------");
        getContentPane().add(lblAcoutBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, -1, -1));

        jLabel7.setText("Encendido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 86, -1, -1));

        lblOn.setText("----------");
        getContentPane().add(lblOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 86, -1, -1));

        btnOnOf.setText("Encender/apagar");
        btnOnOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnOfActionPerformed(evt);
            }
        });
        getContentPane().add(btnOnOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, -1, -1));

        btnChargeCellphone.setText("Cargar movil");
        btnChargeCellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeCellphoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnChargeCellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 115, -1, -1));

        btnRechargeAcountBalance.setText("Recargar saldo");
        btnRechargeAcountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechargeAcountBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnRechargeAcountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, -1, -1));

        btnUseCellphone.setText("Usar movil");
        btnUseCellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUseCellphoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnUseCellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 150, -1, -1));

        btnCall.setText("Realizar llamada");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });
        getContentPane().add(btnCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 185, -1, -1));

        txtNumber.setText("-----------");
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnOfActionPerformed
        // TODO add your handling code here:
        if (cellphone.isOn() == false && cellphone.getBatery()>5) {
            cellphone.setOn(true);
            
            btnUseCellphone.enable(true);
            btnUseCellphone.setVisible(true);
            btnCall.enable(true);
            btnCall.setVisible(true);
        }else{
            btnUseCellphone.enable(false);
            btnUseCellphone.setVisible(false);
            btnCall.enable(false);
            btnCall.setVisible(false);
            cellphone.setOn(false);
            JOptionPane.showMessageDialog(rootPane, "Recarge la bateria");
        }
        refresh(cellphone);
        condition(cellphone);
    }//GEN-LAST:event_btnOnOfActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (cellphone.isOn() == false) {
            btnUseCellphone.enable(false);
            btnUseCellphone.setVisible(false);
            btnCall.enable(false);
            btnCall.setVisible(false);
            cellphone.setOn(false);
        }
        
        refresh(cellphone);
        condition(cellphone);
    }//GEN-LAST:event_formWindowActivated

    private void btnChargeCellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeCellphoneActionPerformed
        // TODO add your handling code here:
        cellphone.setBatery(100);
        refresh(cellphone);
        condition(cellphone);
    }//GEN-LAST:event_btnChargeCellphoneActionPerformed

    private void btnRechargeAcountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechargeAcountBalanceActionPerformed
        // TODO add your handling code here: se aumenta de 50 en 50 
        cellphone.setAcountBalance(cellphone.getAcountBalance() + 50);
        refresh(cellphone);
        condition(cellphone);
    }//GEN-LAST:event_btnRechargeAcountBalanceActionPerformed

    private void btnUseCellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUseCellphoneActionPerformed
        // TODO add your handling code here: baja la bateria de 5 en 5
        if (cellphone.getBatery() > 5) {
            cellphone.setBatery(cellphone.getBatery()-5);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Recarge la bateria");
        }
        refresh(cellphone);  
        condition(cellphone);
    }//GEN-LAST:event_btnUseCellphoneActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        // TODO add your handling code here: 1-12 saldo y -2 bateria agregar condiciones
        if (cellphone.getAcountBalance() > 12 && cellphone.getBatery() > 5) {
            cellphone.setAcountBalance(cellphone.getAcountBalance() - 12);
            cellphone.setBatery(cellphone.getBatery() - 2); 
        } else if (cellphone.getAcountBalance() < 12){
            JOptionPane.showMessageDialog(rootPane, "Recarge saldo");
            btnCall.enable(false);
            btnCall.setVisible(false);
        } 
        else if(cellphone.getBatery() < 2)JOptionPane.showMessageDialog(rootPane, "Recarge la bateria");
            
        refresh(cellphone);
        condition(cellphone);
    }//GEN-LAST:event_btnCallActionPerformed
    private void refresh (Cellphone c){
        c.setNumber(txtNumber.getText());
        this.txtNumber.setText(c.getNumber());
        this.lblBatery.setText(String.valueOf(c.getBatery()));
        this.lblAcoutBalance.setText(String.valueOf(c.getAcountBalance()));
        this.lblOn.setText(String.valueOf(c.isOn()));
    }
    private void condition(Cellphone c){
        if (c.getBatery() <= 5){
            btnUseCellphone.enable(false);
            btnUseCellphone.setVisible(false);
            btnCall.enable(false);
            btnCall.setVisible(false);
            btnOnOf.enable(false);
            btnOnOf.setVisible(false);
        } else {
            btnUseCellphone.enable(true);
            btnUseCellphone.setVisible(true);
            btnCall.enable(true);
            btnCall.setVisible(true);
            btnOnOf.enable(true);
            btnOnOf.setVisible(true);
        }
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnChargeCellphone;
    private javax.swing.JButton btnOnOf;
    private javax.swing.JButton btnRechargeAcountBalance;
    private javax.swing.JButton btnUseCellphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAcoutBalance;
    private javax.swing.JLabel lblBatery;
    private javax.swing.JLabel lblOn;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
